import type { Produto } from '@/types'

async function mockDelay(): Promise<void> {
  await new Promise((r) => setTimeout(r, 80))
}

/** Catálogo mock: até 25 produtos distintos (código + descrição) a partir de Produto.xls — sem repetir itens já listados no arquivo. */
const MOCK_PRODUTOS: Produto[] = [
  {
    id: 1,
    nome: "FR BOM BEBE MEGA G C/70  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 171,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "MEGA",
    codigo: "171",
    psv: 83.72,
    pmv: 90.42,
    puv: 86.23,
    estoque: 422,
    sincronizadoSankhya: true,
  },
  {
    id: 2,
    nome: "FR BOM BEBE MEGA XG C/60  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 172,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "MEGA",
    codigo: "172",
    psv: 80.04,
    pmv: 86.44,
    puv: 82.44,
    estoque: 424,
    sincronizadoSankhya: true,
  },
  {
    id: 3,
    nome: "FR BOM BEBE MEGA XXG C/50  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 173,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "MEGA",
    codigo: "173",
    psv: 85.02,
    pmv: 91.82,
    puv: 87.57,
    estoque: 426,
    sincronizadoSankhya: true,
  },
  {
    id: 4,
    nome: "FR BOM BEBE PRATICA P C/24  - (12X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 174,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "PRATICA",
    codigo: "174",
    psv: 37.1,
    pmv: 40.07,
    puv: 38.21,
    estoque: 428,
    sincronizadoSankhya: false,
  },
  {
    id: 5,
    nome: "FR BOM BEBE PRATICA M C/22  - (12X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 175,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "PRATICA",
    codigo: "175",
    psv: 38.13,
    pmv: 41.18,
    puv: 39.27,
    estoque: 430,
    sincronizadoSankhya: true,
  },
  {
    id: 6,
    nome: "FR BOM BEBE PRATICA G C/20  - (12X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 176,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "PRATICA",
    codigo: "176",
    psv: 39.17,
    pmv: 42.3,
    puv: 40.35,
    estoque: 432,
    sincronizadoSankhya: true,
  },
  {
    id: 7,
    nome: "FR BOM BEBE PRATICA XG C/18  - (12X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 177,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "PRATICA",
    codigo: "177",
    psv: 40.2,
    pmv: 43.42,
    puv: 41.41,
    estoque: 434,
    sincronizadoSankhya: true,
  },
  {
    id: 8,
    nome: "FR BOM BEBE PRATICA XXG C/16 - (12X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 178,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 15.2,
    subgrupo: "PRATICA",
    codigo: "178",
    psv: 41.24,
    pmv: 44.54,
    puv: 42.48,
    estoque: 436,
    sincronizadoSankhya: false,
  },
  {
    id: 9,
    nome: "TIRAS DE FRALDA XXG MÁQUINA 1 MODELO(G)",
    grupo: "FRALDA INFANTIL",
    un: "UN",
    codProd: 210,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 0.042,
    codigo: "210",
    psv: 0.36,
    pmv: 0.39,
    puv: 0.37,
    estoque: 500,
    sincronizadoSankhya: true,
  },
  {
    id: 10,
    nome: "FR GUTO BABY ECO M C/38  - (6X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 368,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 5.5,
    subgrupo: "ECONOMICA",
    codigo: "368",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 816,
    sincronizadoSankhya: true,
  },
  {
    id: 11,
    nome: "FR GUTO BABY ECO G C/32  - (6X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 369,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 5.5,
    subgrupo: "ECONOMICA",
    codigo: "369",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 818,
    sincronizadoSankhya: true,
  },
  {
    id: 12,
    nome: "FR GUTO BABY ECO XG C/30 - (6X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 370,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    subgrupo: "ECONOMICA",
    codigo: "370",
    psv: 71.55,
    pmv: 77.27,
    puv: 73.7,
    estoque: 820,
    sincronizadoSankhya: false,
  },
  {
    id: 13,
    nome: "FR GUTO BABY ECO SXG C/28 - (6X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 371,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    subgrupo: "ECONOMICA",
    codigo: "371",
    psv: 71.55,
    pmv: 77.27,
    puv: 73.7,
    estoque: 822,
    sincronizadoSankhya: true,
  },
  {
    id: 14,
    nome: "PALETE PROMOCIONAL INFANTIL G",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 380,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    codigo: "380",
    psv: 71.07,
    pmv: 76.76,
    puv: 73.2,
    estoque: 840,
    sincronizadoSankhya: true,
  },
  {
    id: 15,
    nome: "PALETE PROMOCIONAL INFANTIL XG",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 381,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    codigo: "381",
    psv: 72.11,
    pmv: 77.88,
    puv: 74.27,
    estoque: 842,
    sincronizadoSankhya: true,
  },
  {
    id: 16,
    nome: "FR GUTO BABY HIPER P C/72  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 382,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 8.5,
    codigo: "382",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 844,
    sincronizadoSankhya: false,
  },
  {
    id: 17,
    nome: "FR GUTO BABY HIPER M C/70  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 383,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 8.5,
    subgrupo: "HIPER",
    codigo: "383",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 846,
    sincronizadoSankhya: true,
  },
  {
    id: 18,
    nome: "FR GUTO BABY HIPER G C/60  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 384,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 8.5,
    subgrupo: "HIPER",
    codigo: "384",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 848,
    sincronizadoSankhya: true,
  },
  {
    id: 19,
    nome: "FR GUTO BABY HIPER XG C/50  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 385,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 8.5,
    subgrupo: "HIPER",
    codigo: "385",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 850,
    sincronizadoSankhya: true,
  },
  {
    id: 20,
    nome: "FR GUTO BABY HIPER SXG C/40  - (4X1)",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 386,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 8.5,
    subgrupo: "HIPER",
    codigo: "386",
    psv: 74.99,
    pmv: 80.99,
    puv: 77.24,
    estoque: 852,
    sincronizadoSankhya: false,
  },
  {
    id: 21,
    nome: "PALETE PROMOCIONAL INFANTIL M",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 387,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    codigo: "387",
    psv: 21.39,
    pmv: 23.1,
    puv: 22.03,
    estoque: 854,
    sincronizadoSankhya: true,
  },
  {
    id: 22,
    nome: "PALETE PROMOCIONAL INFANTIL SXG",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 388,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    codigo: "388",
    psv: 22.42,
    pmv: 24.21,
    puv: 23.09,
    estoque: 856,
    sincronizadoSankhya: true,
  },
  {
    id: 23,
    nome: "FR GUTO BABY PRATICA P C/20 (12X1) NOVA",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 307,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    subgrupo: "PRATICA",
    codigo: "307",
    psv: 15.65,
    pmv: 16.9,
    puv: 16.12,
    estoque: 694,
    sincronizadoSankhya: true,
  },
  {
    id: 24,
    nome: "FR GUTO BABY PRATICA M C/18 (12X1) NOVA",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 308,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    subgrupo: "PRATICA",
    codigo: "308",
    psv: 15.65,
    pmv: 16.9,
    puv: 16.12,
    estoque: 696,
    sincronizadoSankhya: false,
  },
  {
    id: 25,
    nome: "FR GUTO BABY PRATICA G C/16 (12X1) NOVA",
    grupo: "FRALDA INFANTIL",
    un: "FD",
    codProd: 309,
    referencia: "96190000",
    ativo: true,
    pesoBruto: 6.0,
    subgrupo: "PRATICA",
    codigo: "309",
    psv: 15.65,
    pmv: 16.9,
    puv: 16.12,
    estoque: 698,
    sincronizadoSankhya: true,
  },
]

export interface ListarProdutosParams {
  busca?: string
}

export const produtoService = {
  async listar(_token: string, params: ListarProdutosParams = {}): Promise<Produto[]> {
    await mockDelay()
    let data = [...MOCK_PRODUTOS]

    if (params.busca) {
      const termo = params.busca.toLowerCase()
      data = data.filter(
        (p) =>
          p.nome?.toLowerCase().includes(termo) ||
          (p.codProd != null && String(p.codProd).includes(params.busca!)) ||
          p.grupo?.toLowerCase().includes(termo),
      )
    }
    return data
  },

  async sincronizar(_token: string): Promise<{ sucesso: boolean; mensagem: string; total?: number; inseridos?: number; atualizados?: number }> {
    await mockDelay()
    const total = MOCK_PRODUTOS.length
    const pendentes = MOCK_PRODUTOS.filter((p) => !p.sincronizadoSankhya)
    for (const p of MOCK_PRODUTOS) {
      p.sincronizadoSankhya = true
    }

    const mensagem =
      pendentes.length > 0
        ? `Catálogo sincronizado com o Sankhya.\n\n${pendentes.length} produto(s) receberam confirmação do ERP; os demais já estavam alinhados. Total de ${total} itens na lista.`
        : `Catálogo conferido.\n\nTodos os ${total} produto(s) já estavam sincronizados com o Sankhya — nada pendente.`

    return {
      sucesso: true,
      mensagem,
      total,
      inseridos: pendentes.length,
      atualizados: total,
    }
  },
}
